# Generated by Django 3.0.4 on 2020-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_remove_bike_is_finished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='bike',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
