# Generated by Django 3.0.4 on 2020-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20200523_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='amortisseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='boitier_de_pedalier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='cadre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='cassette',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='chaine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='cintre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='coloris',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='derailleur_arriere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='derailleur_avant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='extras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='fourche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='freins',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='jantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='leviers_de_frein',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='manettes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='moyeux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='pedales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='pedalier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='pneus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='poids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='potence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='rayons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='selle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='tailles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='tige_de_selle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
