# Generated by Django 3.0.4 on 2020-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_auto_20200523_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='moteur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
