# Generated by Django 3.0.4 on 2020-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0010_bike_eclairage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='anti_vol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
