# Generated by Django 3.0.4 on 2020-05-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_bike_anti_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='porte_bagages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
