# Generated by Django 3.0.4 on 2020-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0012_bike_porte_bagages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='consolle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
