# Generated by Django 3.0.4 on 2020-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0015_bike_pratique'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='debattement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
