# Generated by Django 3.0.4 on 2020-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0017_bike_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='infos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
