# Generated by Django 3.0.4 on 2020-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0018_bike_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='suspension',
            field=models.TextField(blank=True, null=True),
        ),
    ]
