# Generated by Django 3.0.4 on 2020-05-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0020_bike_diametre_roues'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='affichage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
